/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe-webhook'
import { Route as OilsIndexRouteImport } from './routes/oils.index'
import { Route as OilsSlugRouteImport } from './routes/oils.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as OilsCompareIndexRouteImport } from './routes/oils.compare.index'
import { Route as OilsComparePairRouteImport } from './routes/oils.compare.$pair'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const OilsIndexRoute = OilsIndexRouteImport.update({
  id: '/oils/',
  path: '/oils/',
  getParentRoute: () => rootRouteImport,
} as any)
const OilsSlugRoute = OilsSlugRouteImport.update({
  id: '/oils/$slug',
  path: '/oils/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OilsCompareIndexRoute = OilsCompareIndexRouteImport.update({
  id: '/oils/compare/',
  path: '/oils/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const OilsComparePairRoute = OilsComparePairRouteImport.update({
  id: '/oils/compare/$pair',
  path: '/oils/compare/$pair',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/oils/$slug': typeof OilsSlugRoute
  '/oils/': typeof OilsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/oils/compare/$pair': typeof OilsComparePairRoute
  '/oils/compare/': typeof OilsCompareIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/oils/$slug': typeof OilsSlugRoute
  '/oils': typeof OilsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/oils/compare/$pair': typeof OilsComparePairRoute
  '/oils/compare': typeof OilsCompareIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/oils/$slug': typeof OilsSlugRoute
  '/oils/': typeof OilsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/oils/compare/$pair': typeof OilsComparePairRoute
  '/oils/compare/': typeof OilsCompareIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/api/stripe-webhook'
    | '/oils/$slug'
    | '/oils/'
    | '/api/auth/$'
    | '/oils/compare/$pair'
    | '/oils/compare/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/api/stripe-webhook'
    | '/oils/$slug'
    | '/oils'
    | '/api/auth/$'
    | '/oils/compare/$pair'
    | '/oils/compare'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/api/stripe-webhook'
    | '/oils/$slug'
    | '/oils/'
    | '/api/auth/$'
    | '/oils/compare/$pair'
    | '/oils/compare/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  LoginRoute: typeof LoginRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  OilsSlugRoute: typeof OilsSlugRoute
  OilsIndexRoute: typeof OilsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  OilsComparePairRoute: typeof OilsComparePairRoute
  OilsCompareIndexRoute: typeof OilsCompareIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oils/': {
      id: '/oils/'
      path: '/oils'
      fullPath: '/oils/'
      preLoaderRoute: typeof OilsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oils/$slug': {
      id: '/oils/$slug'
      path: '/oils/$slug'
      fullPath: '/oils/$slug'
      preLoaderRoute: typeof OilsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oils/compare/': {
      id: '/oils/compare/'
      path: '/oils/compare'
      fullPath: '/oils/compare/'
      preLoaderRoute: typeof OilsCompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oils/compare/$pair': {
      id: '/oils/compare/$pair'
      path: '/oils/compare/$pair'
      fullPath: '/oils/compare/$pair'
      preLoaderRoute: typeof OilsComparePairRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  LoginRoute: LoginRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  OilsSlugRoute: OilsSlugRoute,
  OilsIndexRoute: OilsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  OilsComparePairRoute: OilsComparePairRoute,
  OilsCompareIndexRoute: OilsCompareIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
